### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by 3y3** [3y3/ni-ansi-support#1]
- [ ] Unbundle main script:
  - add browserify for bundling
  - exclude unuseful dependencies
- [ ] Process not only singeline strings in console, but also more compcicated previews
- [ ] Maybe. Process ansi not only in console. Needs extended discussion.
- [ ] Add readme.md
